[package]
name = "kittymc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
kittymc-lib = { path = "../kittymc_lib" }
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros", "net", "io-util"] }
